# Step 1: Use a Maven image to build the project
FROM maven:3.8.1-jdk-11 AS build

# Set the working directory inside the container
WORKDIR /app

# Copy the pom.xml and source code into the container
COPY pom.xml .
COPY src ./src

# Run Maven to build the project (skip tests for faster builds)
RUN mvn clean install -DskipTests

# Step 2: Use OpenJDK to run the built application
FROM openjdk:11-jre-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file generated by Maven from the build image to the current working directory
COPY --from=build /app/target/*.jar app.jar

# Command to run the JAR file
ENTRYPOINT ["java", "-jar", "app.jar"]
